# Generated by Django 5.0.2 on 2024-02-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poi",
            fields=[
                (
                    "poi_internal_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("poi_external_id", models.CharField(max_length=255)),
                ("poi_name", models.CharField(max_length=255)),
                ("poi_latitude", models.FloatField()),
                ("poi_longitude", models.FloatField()),
                ("poi_category", models.CharField(max_length=255)),
                ("poi_ratings", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
