# Generated by Django 5.0.2 on 2024-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("internal_id", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("category", models.CharField(max_length=255)),
                ("ratings", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Poi",
        ),
    ]
