# Generated by Django 5.0.2 on 2024-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poi", "0002_pointofinterest_delete_poi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pointofinterest",
            old_name="ratings",
            new_name="avg_ratings",
        ),
        migrations.RemoveField(
            model_name="pointofinterest",
            name="id",
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="internal_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
